Feat/mkp-details
nftfy/nftfy-frontend pull request #14
Opened 2021-02-03 12:55 UTC by iagocarvalhodev

components of the nft details page

2021-02-04 11:43 UTC, fabriciomirandabr commented on package.json
> +    "@types/react-copy-to-clipboard": "^5.0.0",
This is a dev package

2021-02-04 11:44 UTC, fabriciomirandabr commented on src/__stories__/components/marketplace/BuyNftButton.stories.tsx
> +// also exported from '@storybook/react' if you can deal with breaking changes in 6.1
This is one button with different states

2021-02-04 11:44 UTC, fabriciomirandabr commented on src/__stories__/components/marketplace/NftBuyShareDetails.stories.tsx
> +// also exported from '@storybook/react' if you can deal with breaking changes in 6.1
This is one button with different states

2021-02-04 11:44 UTC, fabriciomirandabr commented on src/__stories__/components/marketplace/NftBuyShareDetails.stories.tsx
> +// also exported from '@storybook/react' if you can deal with breaking changes in 6.1
shared/buttons

2021-02-04 11:44 UTC, fabriciomirandabr commented on src/__stories__/components/marketplace/BuyNftButton.stories.tsx
> +// also exported from '@storybook/react' if you can deal with breaking changes in 6.1
shared/buttons

2021-02-04 11:46 UTC, fabriciomirandabr commented on src/__stories__/components/marketplace/NftImage.stories.tsx
> +// also exported from '@storybook/react' if you can deal with breaking changes in 6.1
Isolate by context  

marketplace/details

2021-02-04 11:46 UTC, fabriciomirandabr commented on src/__stories__/components/marketplace/NftInfoDetails.stories.tsx
> +// also exported from '@storybook/react' if you can deal with breaking changes in 6.1
Isolate by context

marketplace/details

2021-02-04 11:47 UTC, fabriciomirandabr commented on src/__stories__/components/marketplace/NftImage.stories.tsx
> +// also exported from '@storybook/react' if you can deal with breaking changes in 6.1
Isolate by context

marketplace/detail

2021-02-04 11:47 UTC, fabriciomirandabr commented on src/__stories__/components/marketplace/NftInfoDetails.stories.tsx
> +// also exported from '@storybook/react' if you can deal with breaking changes in 6.1
Isolate by context

marketplace/detail

2021-02-04 11:47 UTC, fabriciomirandabr commented on src/__stories__/components/marketplace/ShareStatsNftDetails.stories.tsx
> +// also exported from '@storybook/react' if you can deal with breaking changes in 6.1
Isolate by context

marketplace/detail

2021-02-04 11:47 UTC, fabriciomirandabr commented on src/__stories__/components/marketplace/TitleNftDetails.stories.tsx
> +// also exported from '@storybook/react' if you can deal with breaking changes in 6.1
Isolate by context

marketplace/detail

2021-02-04 11:48 UTC, fabriciomirandabr commented on src/components/marketplace/BuyNftButton.tsx
> +import React from 'react'
This is a generic button with different states

2021-02-04 11:49 UTC, fabriciomirandabr commented on src/components/marketplace/BuyNftButton.tsx
> +import React from 'react'
shared/button

different sizes

2021-02-04 11:49 UTC, fabriciomirandabr commented on src/components/marketplace/NftBuyShareDetails.tsx
> +import { Button, Tooltip } from 'antd'
Isolate by context

marketplace/detail

2021-02-04 11:50 UTC, fabriciomirandabr commented on src/components/marketplace/NftImage.tsx
> +/* eslint-disable react/prop-types */
remove

2021-02-04 11:50 UTC, fabriciomirandabr commented on src/components/marketplace/NftImage.tsx
> +        <img src={image || notFound} alt='teste' />
Teste?

2021-02-04 11:50 UTC, fabriciomirandabr commented on src/components/marketplace/NftInfoDetails.tsx
> +/* eslint-disable react/prop-types */
remove

2021-02-04 11:50 UTC, fabriciomirandabr commented on src/components/marketplace/ShareStatsNftDetails.tsx
> +/* eslint-disable react/jsx-one-expression-per-line */
remove

2021-02-04 11:51 UTC, fabriciomirandabr commented on src/components/marketplace/ShareStatsNftDetails.tsx
> +/* eslint-disable react/prop-types */
remove

2021-02-04 11:52 UTC, fabriciomirandabr requested changes
isolate the components from marketplace details inside 

marketplace/details  folder

2021-02-05 13:07 UTC, iagocarvalhodev commented on package.json
> +    "@types/react-copy-to-clipboard": "^5.0.0",
it has to be in dependencies if it won't give an error

2021-02-05 13:27 UTC, fabriciomirandabr commented
@iagocarvalhodev update

2021-02-05 15:10 UTC, fabriciomirandabr approved these changes

2021-02-05 15:10 UTC, merged