create footer
nftfy/nftfy-frontend pull request #6
Opened 2021-01-22 14:14 UTC by iagocarvalhodev

creating the footer component, using the svg icons

2021-01-22 21:08 UTC, fabriciomirandabr commented
Change Title: Added Footer

Color Wrong
Space Wrong
Font Wrong
Size Wrong

Should be PERFECT PIXEL Like Figma

![image](https://user-images.githubusercontent.com/41630011/105546574-50050980-5cdc-11eb-8fe3-6e20b42d2c51.png)

![image](https://user-images.githubusercontent.com/41630011/105547006-cc97e800-5cdc-11eb-897d-2716a6b67132.png)

2021-01-22 21:09 UTC, fabriciomirandabr commented
Code Pattern OK

2021-01-22 21:10 UTC, fabriciomirandabr commented on src/components/shared/footer.tsx
> +    color: #000000;
Colors should come from styles/variables.ts

2021-01-22 21:10 UTC, fabriciomirandabr requested changes
The layout should be perfect pixel

2021-01-23 01:11 UTC, iagocarvalhodev commented on src/components/shared/footer.tsx
> +    color: #000000;
done

2021-01-23 11:51 UTC, fabriciomirandabr commented
![image](https://user-images.githubusercontent.com/41630011/105577397-212c7900-5d58-11eb-98c5-ef55366db26e.png)
Font import in storybook it's no right

2021-01-23 11:52 UTC, fabriciomirandabr commented
The size of   pipe it's not right

![image](https://user-images.githubusercontent.com/41630011/105577413-4325fb80-5d58-11eb-9f4f-43c5dc259409.png)

2021-01-23 11:53 UTC, fabriciomirandabr commented
The box size in large screen it's not right

![image](https://user-images.githubusercontent.com/41630011/105577436-6b155f00-5d58-11eb-92b4-5c244872b409.png)

2021-01-23 11:56 UTC, fabriciomirandabr commented
Missformated in the tablet mode

![image](https://user-images.githubusercontent.com/41630011/105577497-d5c69a80-5d58-11eb-8e2b-f27be4f3eddf.png)

2021-01-23 11:56 UTC, fabriciomirandabr commented
Missformated in large mobile

![image](https://user-images.githubusercontent.com/41630011/105577510-e8d96a80-5d58-11eb-83f1-046488d80f10.png)

2021-01-23 11:57 UTC, fabriciomirandabr commented
Missformated in small mobile

![image](https://user-images.githubusercontent.com/41630011/105577523-f8f14a00-5d58-11eb-8cb2-1706aca35978.png)

2021-01-23 11:58 UTC, fabriciomirandabr commented on public/index.html
> +    <link rel="preconnect" href="https://fonts.gstatic.com" />
What is this?

2021-01-23 11:59 UTC, closed without merging