added nft card
nftfy/nftfy-frontend pull request #9
Opened 2021-01-25 03:03 UTC by iagocarvalhodev

2021-01-26 13:21 UTC, fabriciomirandabr requested changes
Is missing the "Image Breaking"
![image](https://user-images.githubusercontent.com/41630011/105849826-a9f91e00-5fbf-11eb-82a3-eed7a588f43a.png)

Is missing the "Background"
![image](https://user-images.githubusercontent.com/41630011/105849797-a2d21000-5fbf-11eb-92c7-e8878fb718f5.png)

Is missing the hover state, when the user passes the mouse over (request the layout)

Is missing the link action on the card, what happens when the user clicks over the card?

The structure of the card is wrong, is missing the nft name, a the format are wrongs

![image](https://user-images.githubusercontent.com/41630011/105850259-46bbbb80-5fc0-11eb-91bc-ab2373d23a67.png)

2021-01-26 13:21 UTC, fabriciomirandabr commented on src/__stories__/components/marketplace/NftCard.stories.tsx
> +    'https://s3-alpha-sig.figma.com/img/619e/9b53/7bb61c0fedcbbfd82a50ce82213996ce?Expires=1612742400&Signature=PL3I9ax10PFCG~Tx2kj6nDA84vIgORk5NYN2MWUuN2Ud6fjWsK13~SefZ2DQMAXrJqwjfVZ35g1cY5~k3qDXvSA
Import the images from project, create assets folder inside storybook.

Who guarantees that files won't stop working?

2021-01-26 13:21 UTC, fabriciomirandabr commented on src/__stories__/components/marketplace/NftCard.stories.tsx
> +    'https://s3-alpha-sig.figma.com/img/05f2/fd13/118ebd60a3185f76eb6d66fa5edd4208?Expires=1612742400&Signature=BwuH8vJDpo-zeEb6lzPj~oCkgELn21uKKuQd7CNChiXb1wi2e6XrVcw0vTgGN0lzjA7IWOSsDR6GUcS37I4Mh54
move to assets folder

2021-01-26 13:21 UTC, fabriciomirandabr commented on src/__stories__/components/marketplace/NftCard.stories.tsx
> +    'https://s3-alpha-sig.figma.com/img/8a33/4532/6c677f949bce799a74f2b09b7da5ea04?Expires=1612742400&Signature=gYiNJWYP3uoVsjXR78ymsdyzZ6~dim6Z9LaVL7W5bJHntVgk68xOb4o1AIBM4DIUi5HayqjF2u3B7UFz71XB77C
move to assets folder

2021-01-26 13:21 UTC, fabriciomirandabr commented on src/__stories__/components/marketplace/NftCard.stories.tsx
> +    'https://s3-alpha-sig.figma.com/img/05f2/fd13/118ebd60a3185f76eb6d66fa5edd4208?Expires=1612742400&Signature=BwuH8vJDpo-zeEb6lzPj~oCkgELn21uKKuQd7CNChiXb1wi2e6XrVcw0vTgGN0lzjA7IWOSsDR6GUcS37I4Mh54
move to assets folder

2021-01-26 13:21 UTC, fabriciomirandabr commented on src/components/marketplace/NftCard.tsx
> +/* eslint-disable react/prop-types */
remove this line, you should not break eslint rules

2021-01-26 13:21 UTC, fabriciomirandabr commented on src/components/marketplace/NftCard.tsx
> +  imgUrl?: string
rename: image

convert to required, every nft should have and URL, if the URL is empty you should verify inside component

2021-01-26 13:21 UTC, fabriciomirandabr commented on src/components/marketplace/NftCard.tsx
> +                {price}
`TEMPLATE STRING ${VAR}`

2021-01-26 13:21 UTC, fabriciomirandabr commented on src/components/marketplace/NftCard.tsx
> +        <div className='text-info'>
You dont need class here, use sass or styled component

2021-01-26 13:21 UTC, fabriciomirandabr commented on src/styles/variables.tsx
> +export const viewport = {
xs: 0,
  sm: 576px,
  md: 768px,
  lg: 992px,
  xl: 1200px,
  xxl: 1400px

2021-01-26 13:21 UTC, fabriciomirandabr commented on src/components/marketplace/NftCard.tsx
> +    max-width: 304px;
Put a min-height, because if some image comes in a strange format, this will break the layout

2021-01-26 13:21 UTC, fabriciomirandabr commented on src/__stories__/components/marketplace/NftCard.stories.tsx
> +ImgSquare.args = {
Square

2021-01-26 13:21 UTC, fabriciomirandabr commented on src/__stories__/components/marketplace/NftCard.stories.tsx
> +ImgRectangle.args = {
Rectangle

2021-01-28 17:32 UTC, iagocarvalhodev commented on src/styles/variables.tsx
> +export const viewport = {
done

2021-01-29 15:43 UTC, fabriciomirandabr approved these changes

2021-01-29 15:43 UTC, merged